// Reviewed product descriptions only. No repository text is inserted into scripts.
// Each tuple: purpose headline, source-backed description, illustrated workflow, genre.
export const curation = {
  'orthogonal-router-rust-lab': ['Same routes. New kernel.', 'A Rust diagram-router port measured against its unchanged TypeScript reference.', ['Replay a diagram', 'Compare exact paths', 'Inspect measurements'], 'library'],
  trailbraid: ['Two routes. One shared view.', 'Compare GPX geometry and elevation windows with Turf 7.4.0, entirely in the browser.', ['Compare two routes', 'Move the distance window', 'Export route notes'], 'outdoors'],
  framebreak: ['Find takeoff. Loop the landing.', 'MediaBunny 1.61.0 powers local practice-video inspection and silent clip exports.', ['Open a local video', 'Mark a practice attempt', 'Export a silent clip'], 'app'],
  'pocket-park': ['One push. Three little rings.', 'Five small momentum puzzles use Planck 1.5.0 for collisions and 120 Hz physics.', ['Adjust the push', 'Collect three rings', 'Find a soft landing'], 'game'],
  'elsewhere-by-post': ['Turn a place. Swap the world.', 'Six postcard puzzles with quarter-turn roads, stamps and compass-sensitive echo doors.', ['Turn a postcard', 'Align an echo', 'Send the courier'], 'game'],
  'holdfast-local': ['Keep the proof.', 'A local receipt cabinet with recorded return/warranty timelines and proof-packet exports.', ['Import a receipt', 'Verify the policy', 'Export the proof'], 'app'],
  lanternwake: ['Borrow help from yourself.', 'A quiet four-room puzzle where rewinding leaves echoes of your earlier walks.', ['Walk to a pad', 'Leave an echo', 'Reach the bell'], 'game'],
  'leavewell-departure-planner': ['Leave with room to spare.', 'An offline planner that works backward from an arrival deadline using editable uncertainty.', ['Set the deadline', 'Edit the steps', 'Compare departures'], 'app'],
  'oral-board-local-lab': ['A bounded local experiment.', 'A local MLX LoRA research pipeline. Corpus, generated data and model weights are not shown.', ['Experiment code', 'Bounded run', 'Aggregate evaluation'], 'structure'],
  'second-helping-meal-remixer': ['Dinner, with a second act.', 'An offline meal remixer with explicit quantities, substitutions and a planned second meal.', ['Use the pantry', 'Cook the batch', 'Remix the leftovers'], 'app'],
  spoonworld: ['A tiny world. A pinch of wonder.', 'A fictional ingredient ecology toy with seeded bowl-worlds, sproutlings and a field guide.', ['Sprinkle a pantry item', 'Watch the ecology', 'Find a discovery'], 'game'],
  'system-design-chatgpt': ['Draw the system together.', 'A standalone Excalidraw collaboration experiment with a ChatGPT extension protocol.', ['Open a board', 'Share the diagram', 'Review the trade-off'], 'app'],
  'paper-options-lab': ['Keep the replay on paper.', 'A paper-only research and synthetic scenario replay prototype. No trading actions or financial records are shown.', ['Research structure', 'Synthetic replay', 'Review limitations'], 'structure'],
  '.dotfiles': ['A setup worth repeating.', 'A macOS development setup with managed configuration and bootstrap tooling.', ['Configure', 'Bootstrap', 'Repeat'], 'structure'],
  agents: ['One gateway. Focused work.', 'Go-hosted ADK agents with AG-UI endpoints and SQLite sessions.', ['Client', 'Agent gateway', 'SQLite'], 'backend'],
  'agents-mobile': ['Your plans, in your pocket.', 'An Expo client for travel, grocery, fitness and wellness workflows.', ['Choose a tab', 'Refine a plan', 'Review state'], 'app'],
  'ai-shopping-mcp': ['Dinner, meet the list.', 'OAuth-protected grocery tools and an interactive MCP App.', ['Meal context', 'Product matches', 'Review list'], 'app'],
  'better-bracket': ['Make the call.', 'Tournament groups, bracket picks and recorded results.', ['Join a group', 'Make picks', 'Follow results'], 'app'],
  'cavity-game': ['A small world. A smile.', 'A single-player 3D clinic game with fictional visits and collectible stickers.', ['Explore', 'Play a visit', 'Collect stickers'], 'game'],
  'delivery-dash': ['The harbor is your racetrack.', 'A multiplayer coastal delivery game with four source-documented modes.', ['Pick up', 'Race the route', 'Drop off'], 'game'],
  documentation: ['Explain the form.', 'An owned fork of the React Hook Form documentation website.', ['Guides', 'Examples', 'Reference'], 'structure'],
  'garmin-friend-finder': ['Keep the crew in view.', 'A location-sharing prototype with a map and SQLite-backed coordinates.', ['Stored coordinates', 'Map projection', 'Friend list'], 'outdoors'],
  'grocery-agent-mobile': ['Make a plan. Share the shop.', 'An Expo grocery planner with saved recipes, lists and household sharing.', ['Meal ideas', 'Review a list', 'Share with home'], 'app'],
  'happy-birthday-yani': ['A little surprise.', 'A birthday microsite with a reveal, celebration and slideshow structure.', ['Reveal', 'Celebrate', 'Remember'], 'structure'],
  'janella-cookbook': ['Keep the good recipes.', 'Recipe intake, organization, filters and keyword search in one collection.', ['Save a recipe', 'Filter the book', 'Find dinner'], 'app'],
  'keyboard-studio': ['A tiny command center.', 'A SwiftUI configurator for the SayoDevice O2L V2 with a Codex status deck.', ['Stage a layer', 'Review changes', 'Save to device'], 'hardware'],
  leetcode: ['Practice the pattern.', 'Study apps, an extension and a problem collection in a pnpm monorepo.', ['Learn a pattern', 'Try a problem', 'Review a solution'], 'library'],
  'live-auction': ['One room. The latest bid.', 'A Cloudflare live-auction demo with Durable Object state and WebSockets.', ['Bid request', 'Auction state', 'Broadcast'], 'backend'],
  'lucas-plugins': ['Tools for the next task.', 'Portable plugin manifests connect compatible clients to hosted MCP tools.', ['Client', 'Plugin manifest', 'MCP service'], 'library'],
  'lucasarango.space': ['Work, made browsable.', 'A personal portfolio, blog and work-exploration interface.', ['Portfolio', 'Writing', 'Work interface'], 'structure'],
  'machine-learning': ['What changed on the shelf?', 'An OpenCV scene-change detector with a CLI, benchmarks and comparison gallery.', ['Before photo', 'Compare geometry', 'Highlight changes'], 'library'],
  'multiplayer-chat': ['Bring the whole room.', 'Relay shares a coding-agent event stream, permissions, diffs and revisions.', ['Shared room', 'Ordered events', 'Review revision'], 'backend'],
  'neetcode-submissions': ['A record of practice.', 'A topic-organized collection of coding-problem submissions.', ['Topic folders', 'Problem IDs', 'Saved solutions'], 'structure'],
  obsidian: ['A private knowledge space.', 'A private repository containing a personal knowledge-vault structure.', ['Repository', 'Document structure', 'Private contents'], 'structure'],
  'onsite-lab': ['Think. Build. Explain.', 'A browser-local technical interview practice lab with timed workflows.', ['Pick an exercise', 'Work to a timer', 'Review attempt'], 'app'],
  'oral-boards': ['A focused study space.', 'Study software with timed sessions, search and recap structure.', ['Session structure', 'Search interface', 'Recap layout'], 'structure'],
  'pantry-pulse': ['Know what is in the pantry.', 'An RFID pantry station and inventory interface using Cloudflare D1.', ['Scan an item', 'Inventory event', 'Review quantity'], 'hardware'],
  'pediatric-interviewer-esp32': ['Practice, on a small device.', 'An ESP32-S3 study trainer with web setup and a Cloudflare Worker.', ['Web setup', 'Device session', 'Worker interface'], 'hardware'],
  'raleigh-travel': ['A guide for the weekend.', 'A static trip-guide structure with maps and logistics sections.', ['Guide sections', 'Map interface', 'Logistics layout'], 'structure'],
  'react-hook-form-mantine': ['Give your form a name.', 'Mantine inputs wired to React Hook Form through name and control.', ['Mantine field', 'name + control', 'React Hook Form'], 'library'],
  reminder: ['Remember the little things.', 'A legacy PHP reminder interface with SMTP support.', ['Write a reminder', 'Store the request', 'Mail interface'], 'backend'],
  resume: ['One source. Two outputs.', 'A resume build pipeline with private PDF and redacted public output structure.', ['Structured source', 'Build pipeline', 'Redacted output'], 'structure'],
  'resume-carlos': ['A document, structured.', 'A private resume repository. Content is withheld from this film.', ['Source structure', 'Document build', 'Private artifact'], 'structure'],
  'resume-chat': ['Ask about the work.', 'A resume-exploration chat interface with streaming model responses.', ['Question interface', 'Streaming response', 'Review the answer'], 'structure'],
  'resume-template': ['Structure into a document.', 'Reusable JSON Resume to LaTeX/PDF templates and GitHub Actions.', ['JSON structure', 'LaTeX template', 'PDF build'], 'library'],
  'resume-yani': ['A repeatable document build.', 'A private resume source and generated CV-artifact structure.', ['Structured source', 'Shared template', 'Private artifact'], 'structure'],
  'rippling-tech-screen': ['Make the boundary explicit.', 'Two independent Java backend-practice exercises with executable tests.', ['Small API', 'Boundary case', 'Test contract'], 'library'],
  'samsara-java-screen-practice': ['Think aloud. Make it correct.', 'Ten staged Java 21 practice exercises with starters and reference solutions.', ['Starter', 'Follow-up', 'Executable checks'], 'library'],
  'set-and-signal': ['Make the next set obvious.', 'A self-hostable workout planner and training log with account-scoped data.', ['Plan a session', 'Log a set', 'Review history'], 'app'],
  'shipshape-mcp': ['Know what to fix next.', 'Read-only public GitHub signals turned into evidence-backed maintenance priorities.', ['portfolio_snapshot', 'repo_readiness', 'action_plan'], 'backend'],
  snaphaul: ['Clear the blank listing.', 'Photo-to-listing suggestions for several marketplaces, with human review.', ['Item photos', 'Draft listing', 'Seller review'], 'app'],
  'software-eng': ['A small sensor system.', 'A legacy Raspberry Pi sensor dashboard and HTTP API project.', ['Sensor', 'HTTP API', 'Dashboard'], 'hardware'],
  'spring-todo-api': ['A small API. Real boundaries.', 'Owner-scoped Spring Boot todo records, PostgreSQL and Redis caching.', ['OIDC identity', 'Owner-scoped API', 'PostgreSQL'], 'backend'],
  symphony: ['Manage the work.', 'An owned fork of an experimental isolated implementation-run system.', ['Work item', 'Isolated run', 'Evidence review'], 'backend'],
  'system-design-companion': ['Draw the trade-off.', 'A realtime Excalidraw board shared by people and MCP agents.', ['Shared board', 'Add a component', 'Discuss trade-offs'], 'app'],
  'trading-mcp': ['A structured tool surface.', 'An MCP and HTTP interface for market-data and trading integrations.', ['Tool interface', 'Provider adapter', 'Typed response'], 'structure'],
  traillib: ['Find the trail reports.', 'A standalone trail-source library, maintained from a separate monorepo.', ['Trail query', 'Source adapters', 'Grouped reports'], 'outdoors'],
  traverse: ['From trail question to plan.', 'A Bun trail-research pipeline with a web app, API, queue and worker.', ['Trail question', 'Queued report', 'Hike-plan interface'], 'outdoors'],
  trvl: ['Ask for the trade-offs.', 'A Go travel CLI and MCP server with structured provider results.', ['Trip constraints', 'Provider adapters', 'Structured results'], 'outdoors'],
  'vienna-travel': ['Coffee. Lakes. Alpine trails.', 'A ten-day Austrian travel guide with maps, timeline and packing interfaces.', ['Explore the route', 'Open a day', 'Review the pack'], 'outdoors'],
};
export const changes = {
 'orthogonal-router-rust-lab':'Merged: a measured compatibility lab.',
 trailbraid:'Merged: a local GPX comparison atlas.',
 framebreak:'Merged: a private practice-video workbench.',
 'pocket-park':'Merged: five small physics parks.',
 agents:'Active-run ownership and atomic saved-list edits.',
 'agents-mobile':'Resumable sync and visible submission failures.',
 'ai-shopping-mcp':'Bounded catalog requests and list enrichment.',
 'garmin-friend-finder':'Authenticated ownership proposal. Device migration still required.',
 'onsite-lab':'Autosave retention and serialized completion proposal.',
 'pantry-pulse':'Concurrent inventory corrections guarded atomically.',
 'set-and-signal':'Retain queued edits when local storage fails.',
 'trading-mcp':'Unavailable-history guards in technical-analysis responses.',
 traverse:'Generation-aware ingestion and retry-safe report publication.',
 'delivery-dash':'Current Cloudflare CLI preserves existing Worker secrets.',
};
